<a href="https://colab.research.google.com/github/VyshnavipriyaChintapalli/Practice/blob/me/Final_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
      print(os.path.join(dirname, filename))

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [ ]:
df1 = pd.read_csv("/content/Fake Postings.csv")

In [ ]:
df1

,title,description,requirements,company_profile,location,salary_range,employment_type,industry,benefits,fraudulent
0,Mental health nurse,Arm drive court sure vote. Earn $5000/week! Im...,"Basic knowledge in live, no degree required. F...",Rivera and Sons - Established 2022.,West Jeffrey,$55016-$100476,Internship,IT,Free meals,1
1,Conference centre manager,Government whom its bed go tax tree black. Ear...,"Basic knowledge in seek, no degree required. F...","Davidson, Jones and Gomez - Established 2003.",Lake Meredithberg,$53438-$93138,Part-Time,Finance,Flexible hours,1
2,"Engineer, land",I member discuss follow way there nation. Earn...,"Basic knowledge in worker, no degree required....",Allen Ltd - Established 1998.,Lake Cathybury,$45584-$105229,Part-Time,IT,Free travel,1
3,Forest/woodland manager,House across wait approach face. Earn $5000/we...,"Basic knowledge in example, no degree required...",Forbes Ltd - Established 1990.,South Matthewstad,$66188-$139621,Full-Time,Education,Free travel,1
4,"Production designer, theatre/television/film",Case best environmental full finally leader me...,"Basic knowledge in smile, no degree required. ...","Jennings, Martin and Sanchez - Established 1975.",East Rhondafurt,$32183-$115012,Temporary,Retail,Flexible hours,1
...,...,...,...,...,...,...,...,...,...,...
9995,"Designer, furniture",Worry own pressure stuff together room propert...,"Basic knowledge in discussion, no degree requi...",Olson-Williams - Established 2017.,Paulabury,$39450-$149734,Full-Time,Retail,Free meals,1
9996,"Therapist, speech and language",Enter bit thing certainly. Earn $5000/week! Im...,"Basic knowledge in value, no degree required. ...",Moreno-Pruitt - Established 2016.,Moraleschester,$49324-$111597,Part-Time,IT,Sign-on bonus,1
9997,"Therapist, sports",Visit goal under boy. Earn $5000/week! Immedia...,"Basic knowledge in during, no degree required....","Lewis, Patterson and Cowan - Established 1979.",Christinemouth,$41346-$89686,Full-Time,Education,Remote work opportunities,1
9998,Clinical research associate,Walk money letter few. Earn $5000/week! Immedi...,"Basic knowledge in can, no degree required. Fl...",Diaz-Wilkerson - Established 2019.,Lake Meredithberg,$65604-$149614,Contract,Finance,Flexible hours,1
9999,Hospital pharmacist,Other left TV each reveal. Earn $5000/week! Im...,"Basic knowledge in pick, no degree required. F...","Sanders, Sanchez and Cox - Established 2024.",Samanthaland,$56437-$112301,Temporary,Real Estate,Free meals,1

In [ ]:
df2 = pd.read_csv("/content/fake_job_postings.csv")

In [ ]:
df2

,job_id,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent
0,1,Marketing Intern,"US, NY, New York",Marketing,NaN,"We're Food52, and we've created a groundbreaki...","Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,NaN,0,1,0,Other,Internship,NaN,NaN,Marketing,0
1,2,Customer Service - Cloud Video Production,"NZ, , Auckland",Success,NaN,"90 Seconds, the worlds Cloud Video Production ...",Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,What you will get from usThrough being part of...,0,1,0,Full-time,Not Applicable,NaN,Marketing and Advertising,Customer Service,0
2,3,Commissioning Machinery Assistant (CMA),"US, IA, Wever",NaN,NaN,Valor Services provides Workforce Solutions th...,"Our client, located in Houston, is actively se...",Implement pre-commissioning and commissioning ...,NaN,0,1,0,NaN,NaN,NaN,NaN,NaN,0
3,4,Account Executive - Washington DC,"US, DC, Washington",Sales,NaN,Our passion for improving quality of life thro...,THE COMPANY: ESRI – Environmental Systems Rese...,"EDUCATION: Bachelor’s or Master’s in GIS, busi...",Our culture is anything but corporate—we have ...,0,1,0,Full-time,Mid-Senior level,Bachelor's Degree,Computer Software,Sales,0
4,5,Bill Review Manager,"US, FL, Fort Worth",NaN,NaN,SpotSource Solutions LLC is a Global Human Cap...,JOB TITLE: Itemization Review ManagerLOCATION:...,QUALIFICATIONS:RN license in the State of Texa...,Full Benefits Offered,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Hospital & Health Care,Health Care Provider,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17875,17876,Account Director - Distribution,"CA, ON, Toronto",Sales,NaN,Vend is looking for some awesome new talent to...,Just in case this is the first time you’ve vis...,To ace this role you:Will eat comprehensive St...,What can you expect from us?We have an open cu...,0,1,1,Full-time,Mid-Senior level,NaN,Computer Software,Sales,0
17876,17877,Payroll Accountant,"US, PA, Philadelphia",Accounting,NaN,WebLinc is the e-commerce platform and service...,The Payroll Accountant will focus primarily on...,- B.A. or B.S. in Accounting- Desire to have f...,Health &amp; WellnessMedical planPrescription ...,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Internet,Accounting/Auditing,0
17877,17878,Project Cost Control Staff Engineer - Cost Con...,"US, TX, Houston",NaN,NaN,We Provide Full Time Permanent Positions for m...,Experienced Project Cost Control Staff Enginee...,At least 12 years professional experience.Abil...,NaN,0,0,0,Full-time,NaN,NaN,NaN,NaN,0
17878,17879,Graphic Designer,"NG, LA, Lagos",NaN,NaN,NaN,Nemsia Studios is looking for an experienced v...,1. Must be fluent in the latest versions of Co...,Competitive salary (compensation will be based...,0,0,1,Contract,Not Applicable,Professional,Graphic Design,Design,0
17879,17880,Web Application Developers,"NZ, N, Wellington",Engineering,NaN,Vend is looking for some awesome new talent to...,Who are we?Vend is an award winning web based ...,We want to hear from you if:You have an in-dep...,NaN,0,1,1,Full-time,Mid-Senior level,NaN,Computer Software,Engineering,0

In [ ]:
df1.columns

Index(['title', 'description', 'requirements', 'company_profile', 'location',
       'salary_range', 'employment_type', 'industry', 'benefits',
       'fraudulent'],
      dtype='object')

In [ ]:
df2.columns

Index(['job_id', 'title', 'location', 'department', 'salary_range',
       'company_profile', 'description', 'requirements', 'benefits',
       'telecommuting', 'has_company_logo', 'has_questions', 'employment_type',
       'required_experience', 'required_education', 'industry', 'function',
       'fraudulent'],
      dtype='object')

In [ ]:
df_merged = pd.concat([df1, df2], ignore_index=True)

In [ ]:
df_merged

,title,description,requirements,company_profile,location,salary_range,employment_type,industry,benefits,fraudulent,job_id,department,telecommuting,has_company_logo,has_questions,required_experience,required_education,function
0,Mental health nurse,Arm drive court sure vote. Earn $5000/week! Im...,"Basic knowledge in live, no degree required. F...",Rivera and Sons - Established 2022.,West Jeffrey,$55016-$100476,Internship,IT,Free meals,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Conference centre manager,Government whom its bed go tax tree black. Ear...,"Basic knowledge in seek, no degree required. F...","Davidson, Jones and Gomez - Established 2003.",Lake Meredithberg,$53438-$93138,Part-Time,Finance,Flexible hours,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"Engineer, land",I member discuss follow way there nation. Earn...,"Basic knowledge in worker, no degree required....",Allen Ltd - Established 1998.,Lake Cathybury,$45584-$105229,Part-Time,IT,Free travel,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Forest/woodland manager,House across wait approach face. Earn $5000/we...,"Basic knowledge in example, no degree required...",Forbes Ltd - Established 1990.,South Matthewstad,$66188-$139621,Full-Time,Education,Free travel,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"Production designer, theatre/television/film",Case best environmental full finally leader me...,"Basic knowledge in smile, no degree required. ...","Jennings, Martin and Sanchez - Established 1975.",East Rhondafurt,$32183-$115012,Temporary,Retail,Flexible hours,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27875,Account Director - Distribution,Just in case this is the first time you’ve vis...,To ace this role you:Will eat comprehensive St...,Vend is looking for some awesome new talent to...,"CA, ON, Toronto",NaN,Full-time,Computer Software,What can you expect from us?We have an open cu...,0,17876.0,Sales,0.0,1.0,1.0,Mid-Senior level,NaN,Sales
27876,Payroll Accountant,The Payroll Accountant will focus primarily on...,- B.A. or B.S. in Accounting- Desire to have f...,WebLinc is the e-commerce platform and service...,"US, PA, Philadelphia",NaN,Full-time,Internet,Health &amp; WellnessMedical planPrescription ...,0,17877.0,Accounting,0.0,1.0,1.0,Mid-Senior level,Bachelor's Degree,Accounting/Auditing
27877,Project Cost Control Staff Engineer - Cost Con...,Experienced Project Cost Control Staff Enginee...,At least 12 years professional experience.Abil...,We Provide Full Time Permanent Positions for m...,"US, TX, Houston",NaN,Full-time,NaN,NaN,0,17878.0,NaN,0.0,0.0,0.0,NaN,NaN,NaN
27878,Graphic Designer,Nemsia Studios is looking for an experienced v...,1. Must be fluent in the latest versions of Co...,NaN,"NG, LA, Lagos",NaN,Contract,Graphic Design,Competitive salary (compensation will be based...,0,17879.0,NaN,0.0,0.0,1.0,Not Applicable,Professional,Design
27879,Web Application Developers,Who are we?Vend is an award winning web based ...,We want to hear from you if:You have an in-dep...,Vend is looking for some awesome new talent to...,"NZ, N, Wellington",NaN,Full-time,Computer Software,NaN,0,17880.0,Engineering,0.0,1.0,1.0,Mid-Senior level,NaN,Engineering

In [ ]:
df_merged.head()

,title,description,requirements,company_profile,location,salary_range,employment_type,industry,benefits,fraudulent,job_id,department,telecommuting,has_company_logo,has_questions,required_experience,required_education,function
0,Mental health nurse,Arm drive court sure vote. Earn $5000/week! Im...,"Basic knowledge in live, no degree required. F...",Rivera and Sons - Established 2022.,West Jeffrey,$55016-$100476,Internship,IT,Free meals,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Conference centre manager,Government whom its bed go tax tree black. Ear...,"Basic knowledge in seek, no degree required. F...","Davidson, Jones and Gomez - Established 2003.",Lake Meredithberg,$53438-$93138,Part-Time,Finance,Flexible hours,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"Engineer, land",I member discuss follow way there nation. Earn...,"Basic knowledge in worker, no degree required....",Allen Ltd - Established 1998.,Lake Cathybury,$45584-$105229,Part-Time,IT,Free travel,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Forest/woodland manager,House across wait approach face. Earn $5000/we...,"Basic knowledge in example, no degree required...",Forbes Ltd - Established 1990.,South Matthewstad,$66188-$139621,Full-Time,Education,Free travel,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"Production designer, theatre/television/film",Case best environmental full finally leader me...,"Basic knowledge in smile, no degree required. ...","Jennings, Martin and Sanchez - Established 1975.",East Rhondafurt,$32183-$115012,Temporary,Retail,Flexible hours,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_merged.tail()

,title,description,requirements,company_profile,location,salary_range,employment_type,industry,benefits,fraudulent,job_id,department,telecommuting,has_company_logo,has_questions,required_experience,required_education,function
27875,Account Director - Distribution,Just in case this is the first time you’ve vis...,To ace this role you:Will eat comprehensive St...,Vend is looking for some awesome new talent to...,"CA, ON, Toronto",NaN,Full-time,Computer Software,What can you expect from us?We have an open cu...,0,17876.0,Sales,0.0,1.0,1.0,Mid-Senior level,NaN,Sales
27876,Payroll Accountant,The Payroll Accountant will focus primarily on...,- B.A. or B.S. in Accounting- Desire to have f...,WebLinc is the e-commerce platform and service...,"US, PA, Philadelphia",NaN,Full-time,Internet,Health &amp; WellnessMedical planPrescription ...,0,17877.0,Accounting,0.0,1.0,1.0,Mid-Senior level,Bachelor's Degree,Accounting/Auditing
27877,Project Cost Control Staff Engineer - Cost Con...,Experienced Project Cost Control Staff Enginee...,At least 12 years professional experience.Abil...,We Provide Full Time Permanent Positions for m...,"US, TX, Houston",NaN,Full-time,NaN,NaN,0,17878.0,NaN,0.0,0.0,0.0,NaN,NaN,NaN
27878,Graphic Designer,Nemsia Studios is looking for an experienced v...,1. Must be fluent in the latest versions of Co...,NaN,"NG, LA, Lagos",NaN,Contract,Graphic Design,Competitive salary (compensation will be based...,0,17879.0,NaN,0.0,0.0,1.0,Not Applicable,Professional,Design
27879,Web Application Developers,Who are we?Vend is an award winning web based ...,We want to hear from you if:You have an in-dep...,Vend is looking for some awesome new talent to...,"NZ, N, Wellington",NaN,Full-time,Computer Software,NaN,0,17880.0,Engineering,0.0,1.0,1.0,Mid-Senior level,NaN,Engineering

In [ ]:
df_merged.columns

Index(['title', 'description', 'requirements', 'company_profile', 'location',
       'salary_range', 'employment_type', 'industry', 'benefits', 'fraudulent',
       'job_id', 'department', 'telecommuting', 'has_company_logo',
       'has_questions', 'required_experience', 'required_education',
       'function'],
      dtype='object')

In [ ]:
df_merged = df_merged.drop(['job_id' , 'title', 'location', 'department', 'salary_range', 'telecommuting', 'has_company_logo', 'has_questions', 'employment_type','required_experience', 'required_education', 'industry', 'function'], axis=1)

In [ ]:
df_merged

,description,requirements,company_profile,benefits,fraudulent
0,Arm drive court sure vote. Earn $5000/week! Im...,"Basic knowledge in live, no degree required. F...",Rivera and Sons - Established 2022.,Free meals,1
1,Government whom its bed go tax tree black. Ear...,"Basic knowledge in seek, no degree required. F...","Davidson, Jones and Gomez - Established 2003.",Flexible hours,1
2,I member discuss follow way there nation. Earn...,"Basic knowledge in worker, no degree required....",Allen Ltd - Established 1998.,Free travel,1
3,House across wait approach face. Earn $5000/we...,"Basic knowledge in example, no degree required...",Forbes Ltd - Established 1990.,Free travel,1
4,Case best environmental full finally leader me...,"Basic knowledge in smile, no degree required. ...","Jennings, Martin and Sanchez - Established 1975.",Flexible hours,1
...,...,...,...,...,...
27875,Just in case this is the first time you’ve vis...,To ace this role you:Will eat comprehensive St...,Vend is looking for some awesome new talent to...,What can you expect from us?We have an open cu...,0
27876,The Payroll Accountant will focus primarily on...,- B.A. or B.S. in Accounting- Desire to have f...,WebLinc is the e-commerce platform and service...,Health &amp; WellnessMedical planPrescription ...,0
27877,Experienced Project Cost Control Staff Enginee...,At least 12 years professional experience.Abil...,We Provide Full Time Permanent Positions for m...,NaN,0
27878,Nemsia Studios is looking for an experienced v...,1. Must be fluent in the latest versions of Co...,NaN,Competitive salary (compensation will be based...,0
27879,Who are we?Vend is an award winning web based ...,We want to hear from you if:You have an in-dep...,Vend is looking for some awesome new talent to...,NaN,0

In [ ]:
df_merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27880 entries, 0 to 27879
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   description      27879 non-null  object
 1   requirements     25184 non-null  object
 2   company_profile  24572 non-null  object
 3   benefits         20668 non-null  object
 4   fraudulent       27880 non-null  int64
dtypes: int64(1), object(4)
memory usage: 1.1+ MB

In [ ]:
df_merged = df_merged.fillna(" ")

In [ ]:
df_merged['description'] = df_merged['description'] + " " + df_merged['company_profile'] + " "+ df_merged['requirements'] + " " +df_merged['benefits']

In [ ]:
df_merged.head()

,description,requirements,company_profile,benefits,fraudulent
0,Arm drive court sure vote. Earn $5000/week! Im...,"Basic knowledge in live, no degree required. F...",Rivera and Sons - Established 2022.,Free meals,1
1,Government whom its bed go tax tree black. Ear...,"Basic knowledge in seek, no degree required. F...","Davidson, Jones and Gomez - Established 2003.",Flexible hours,1
2,I member discuss follow way there nation. Earn...,"Basic knowledge in worker, no degree required....",Allen Ltd - Established 1998.,Free travel,1
3,House across wait approach face. Earn $5000/we...,"Basic knowledge in example, no degree required...",Forbes Ltd - Established 1990.,Free travel,1
4,Case best environmental full finally leader me...,"Basic knowledge in smile, no degree required. ...","Jennings, Martin and Sanchez - Established 1975.",Flexible hours,1

In [ ]:
df_merged.tail()

,description,requirements,company_profile,benefits,fraudulent
27875,Just in case this is the first time you’ve vis...,To ace this role you:Will eat comprehensive St...,Vend is looking for some awesome new talent to...,What can you expect from us?We have an open cu...,0
27876,The Payroll Accountant will focus primarily on...,- B.A. or B.S. in Accounting- Desire to have f...,WebLinc is the e-commerce platform and service...,Health &amp; WellnessMedical planPrescription ...,0
27877,Experienced Project Cost Control Staff Enginee...,At least 12 years professional experience.Abil...,We Provide Full Time Permanent Positions for m...,,0
27878,Nemsia Studios is looking for an experienced v...,1. Must be fluent in the latest versions of Co...,,Competitive salary (compensation will be based...,0
27879,Who are we?Vend is an award winning web based ...,We want to hear from you if:You have an in-dep...,Vend is looking for some awesome new talent to...,,0

In [ ]:
df_merged.columns

Index(['description', 'requirements', 'company_profile', 'benefits',
       'fraudulent'],
      dtype='object')

In [ ]:
df_merged = df_merged.drop(['company_profile', 'requirements','benefits'], axis=1)

In [ ]:
df_merged

                                             description  fraudulent
0      Arm drive court sure vote. Earn $5000/week! Im...           1
1      Government whom its bed go tax tree black. Ear...           1
2      I member discuss follow way there nation. Earn...           1
3      House across wait approach face. Earn $5000/we...           1
4      Case best environmental full finally leader me...           1
...                                                  ...         ...
27875  Just in case this is the first time you’ve vis...           0
27876  The Payroll Accountant will focus primarily on...           0
27877  Experienced Project Cost Control Staff Enginee...           0
27878  Nemsia Studios is looking for an experienced v...           0
27879  Who are we?Vend is an award winning web based ...           0

[27880 rows x 2 columns]

In [ ]:
tfidf_vectorizer = TfidfVectorizer(max_features=5000)

In [ ]:
df_merged.fraudulent.value_counts()

fraudulent
0    17014
1    10866
Name: count, dtype: int64

In [ ]:
df_merged.columns

Index(['description', 'fraudulent'], dtype='object')

In [ ]:
x = tfidf_vectorizer.fit_transform(df_merged['description'])
y = df_merged['fraudulent']

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.1, random_state=20)

In [ ]:
from sklearn.utils.class_weight import compute_class_weight
class_weights = compute_class_weight(class_weight = "balanced" , classes = np.unique(y_train), y = y_train)
class_weights_dict = dict(zip(np.unique(y_train), class_weights))

In [ ]:
svm_model = SVC(kernel='linear', C=2, random_state=20)
svm_model.fit(x_train, y_train)

SVC(C=2, kernel='linear', random_state=20)

In [ ]:
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import accuracy_score

# Define the model using hinge loss (equivalent to SVM)
svm_sgd = SGDClassifier(loss='hinge', learning_rate='optimal', random_state=20)

epochs = 3 # Define number of epochs
for epoch in range(epochs):
    svm_sgd.partial_fit(x_train, y_train, classes=[0, 1])  # Incremental learning
    train_accuracy = accuracy_score(y_train, svm_sgd.predict(x_train))
    print(f"Epoch {epoch + 1}/{epochs} - Training Accuracy: {train_accuracy:.4f}")

# Final evaluation on test set
test_accuracy = accuracy_score(y_test, svm_sgd.predict(x_test))
print(f"Final Test Accuracy: {test_accuracy:.4f}")

Epoch 1/3 - Training Accuracy: 0.9859
Epoch 2/3 - Training Accuracy: 0.9863
Epoch 3/3 - Training Accuracy: 0.9864
Final Test Accuracy: 0.9839

In [ ]:
y_pred = svm_model.predict(x_test)

In [ ]:
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)
confusion = confusion_matrix(y_test, y_pred)

In [ ]:
print("Accuracy:", accuracy)
print("\nClassification Report:\n", report)
print("\nConfusion Matrix:\n", confusion)

Accuracy: 0.9860114777618364

Classification Report:
               precision    recall  f1-score   support

           0       0.98      1.00      0.99      1673
           1       1.00      0.97      0.98      1115

    accuracy                           0.99      2788
   macro avg       0.99      0.98      0.99      2788
weighted avg       0.99      0.99      0.99      2788


Confusion Matrix:
 [[1668    5]
 [  34 1081]]

In [ ]:
def job_post_detection():

    new_job_post = input("Enter the job description: ")

    # Put the new_job_post string inside a list to make it an iterable
    new_job_post_vectorized = tfidf_vectorizer.transform([new_job_post])
    prediction = svm_model.predict(new_job_post_vectorized)

    if prediction[0] == 1:
        print("\nThis job posting is predicted to be FAKE.")
    else:
        print("\nThis job posting is predicted to be REAL.")
job_post_detection()

Enter the job description: A job posting that offers a significantly higher salary than what's typical for the role and experience level is a major warning sign.

This job posting is predicted to be REAL.